name: Run CI
on:
    push:
        branches: [main]
    pull_request:
        branches:
            - '*'

jobs:
  unit_tests:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: iOS build setup
        run: >-
          xcodebuild test -workspace CI.xcodeproj/project.xcworkspace
          -scheme CI -destination 'platform=iOS Simulator,name=iPhone
          11'
