name: Run CI
on:
    push:
        branches: [main]
    pull_request:
        branches:
            - '*'

#on:
#  push:
#    branches:
#    - develop_branch

jobs:
  unit_tests:
    name: Unit testing
    runs-on: macos-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=13.2.2,name=iPhone 11 Pro Max']
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      - name: Build
        run: |
          xcodebuild clean build -project MVP.xcodeproj -scheme MVP -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        env:
         destination: ${{ matrix.destination }}
      - name: Test
        run: |
          xcodebuild clean test -project MVP.xcodeproj -scheme MVPTests -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO | xcpretty && exit ${PIPESTATUS[0]}
        env:
         destination: ${{ matrix.destination }}
